feat(pre-post): prepost message

diff --git a/.husky/pre-push b/.husky/pre-push
--- a/.husky/pre-push
+++ b/.husky/pre-push
@@ -1,4 +1,28 @@
 #!/usr/bin/env sh
 . "$(dirname -- "$0")/_/husky.sh"
-ng lint
 
+echo "Running pre-push checks..."
+
+# Run tests
+echo "Running tests..."
+npm test
+test_status=$?
+
+# Run linting
+echo "Running lint checks..."
+npm run lint
+lint_status=$?
+
+# Run formatting checks
+echo "Checking code formatting..."
+#npm run format:check
+#format_status=1?
+
+# Check if any of the checks failed
+if [ "$test_status" != 0 ] || [ "$lint_status" != 0 ] ; then
+#  || [ "$format_status" != 0 ]
+  echo "Pre-push checks failed. Push aborted."
+  exit 1
+fi
+
+echo "Pre-push checks passed. Proceeding with push."
